In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))

In [5]:
from src.loader import (
    load_history,
    load_close_prices,
)

from src.returns import calculate_returns

from src.metrics import (
    calculate_annual_return,
    calculate_annual_volatility,
    calculate_covariance_matrix,
)

from src.optimizer import optimize_portfolio

In [13]:
tickers = [
    "GAZP",
    "SBER",
    "LKOH",
]

In [14]:
prices = await load_close_prices(tickers)

prices.head()

            GAZP   SBER    LKOH
TRADEDATE
2013-03-25   NaN  98.79  1922.0
2013-03-26   NaN  97.20  1944.5
2013-03-27   NaN  96.75  1969.7
2013-03-28   NaN  98.59  1993.2
2013-03-29   NaN  98.76  2003.4

In [15]:
returns = calculate_returns(prices)

returns.head()

C:\Users\user\Projects\portfolio-optimization\src\returns.py:31: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = prices.pct_change()

            GAZP      SBER      LKOH
TRADEDATE
2013-03-26   NaN -0.016095  0.011707
2013-03-27   NaN -0.004630  0.012960
2013-03-28   NaN  0.019018  0.011931
2013-03-29   NaN  0.001724  0.005117
2013-04-01   NaN -0.006987 -0.012579

In [16]:
annual_returns = calculate_annual_return(returns)

annual_returns

GAZP    0.018391
SBER    0.137096
LKOH    0.105630
dtype: float64

In [17]:
annual_volatility = calculate_annual_volatility(returns)

annual_volatility

GAZP    0.327628
SBER    0.328655
LKOH    0.294451
dtype: float64

In [18]:
covariance_matrix = calculate_covariance_matrix(returns)

covariance_matrix

          GAZP      SBER      LKOH
GAZP  0.107340  0.060568  0.054864
SBER  0.060568  0.108014  0.051338
LKOH  0.054864  0.051338  0.086701

In [19]:
weights = optimize_portfolio(
    annual_returns,
    covariance_matrix,
)

weights

GAZP    0.000000
SBER    0.595964
LKOH    0.404036
Name: Weight, dtype: float64